version: '3'
services:
  db:
    image: postgres:11.6
    container_name: postgres
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  app:
    container_name: issues
    env_file: ./.env
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/auth/signin"]
      interval: 1s
      timeout: 10s
      retries: 10
      start_period: 3s
