version: "3"
services:
  db:
    image: "postgres:11.6"
    container_name: "prisma-pg"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=hilly-sand-pit
      - POSTGRES_DB=prisma
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  maildev:
    image: maildev/maildev
    container_name: "maildev-taskany"
    ports:
      - "1080:1080"
      - "1025:1025"
  app:
    stdin_open: true
    container_name: app
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://prisma:hilly-sand-pit@db:5432/prisma?schema=prisma-pg-test
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=ololo
      - ADMIN_EMAIL=test@taskany.org
      - ADMIN_PASSWORD=test
      - MAIL_USER=notify@taskany.org
      - SENTRY_DISABLED=1
      - SENTRY_IGNORE_API_RESOLUTION_ERROR=1
    command: >
      sh -c "node_modules/.bin/prisma migrate dev &&
             node_modules/.bin/concurrently 'node background/worker/index.js' 'node server.js'"
