version: "3"
services:
  db:
    image: "postgres:11.6"
    container_name: "prisma-pg"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=hilly-sand-pit
      - POSTGRES_DB=prisma
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  maildev:
    image: maildev/maildev
    container_name: "maildev-taskany"
    ports:
      - "1080:1080"
      - "1025:1025"
  nextjs:
    stdin_open: true
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://prisma:hilly-sand-pit@db:5432/prisma?schema=prisma-pg-test
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/auth/signin"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 40s
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:10.0.3"
    depends_on:
      db:
        condition: service_started
      nextjs:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://nextjs:3000
    working_dir: /e2e
    volumes:
      - ./:/e2e
