name: Cypress testing

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/**.json'
      - '**/**.js'
      - '**/**.jsx'
      - '**/**.ts'
      - '**/**.tsx'

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker
        run: docker-compose -f docker-compose.ci.yml up -d
      - name: Run specs
        uses: cypress-io/github-action@v4
