name: Cypress testing

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/**.json'
      - '**/**.js'
      - '**/**.jsx'
      - '**/**.ts'
      - '**/**.tsx'

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        run: docker-compose -f docker-compose.ci.yml up -d
      - name: Run specs
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_ADMIN_EMAIL: test@taskany.org
          CYPRESS_ADMIN_PASSWORD: test
          DATABASE_URL: postgresql://prisma:hilly-sand-pit@localhost:5432/e2e
        with:
          build: npx prisma generate
      - name: Store Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
